---
abstract: 'danish postal order code generator/validator'
author:
  - 'Jonas B. Nielsen, (jonasbn) <jonasbn@cpan.org>'
build_requires: {}
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.142060'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Business-DK-PO
provides:
  Business::DK::PO:
    file: lib/Business/DK/PO.pm
    version: '0.07'
requires:
  Carp: '0'
  Exporter: '0'
  Test::Exception: '0'
  Test::Kwalitee: '0'
  Test::Perl::Critic: '0'
  perl: '5.006'
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Business-DK-PO
  homepage: http://logiclab.jira.com/wiki/display/BDKPO/Home
  license: http://www.perlfoundation.org/artistic_license_1_0
  projectChangelog: http://logiclab.jira.com/browse/BDKPO#selectedTab=com.atlassian.jira.plugin.system.project%3Achangelog-panel
  projectSite: http://logicLAB.jira.com/browse/BDKPO
  projectWiki: http://logiclab.jira.com/wiki/display/BDKPO/Home
  repository: https://github.com/jonasbn/bdkpo
version: '0.07'
