---
abstract: 'danish postal order code generator/validator'
author:
  - 'Jonas B. Nielsen, (jonasbn) <jonasbn@cpan.org>'
build_requires: {}
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.131560'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Business-DK-PO
provides:
  Business::DK::PO:
    file: lib/Business/DK/PO.pm
    version: 0.06
requires:
  Carp: 0
  Exporter: 0
  Test::Exception: 0
  Test::Kwalitee: 0
  Test::Perl::Critic: 0
resources:
  ProjectChangelog: http://logiclab.jira.com/browse/BDKPO#selectedTab=com.atlassian.jira.plugin.system.project%3Achangelog-panel
  ProjectSite: http://logicLAB.jira.com/browse/BDKPO
  ProjectWiki: http://logiclab.jira.com/wiki/display/BDKPO/Home
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Business-DK-PO
  homepage: http://logiclab.jira.com/wiki/display/BDKPO/Home
  license: http://www.perlfoundation.org/artistic_license_1_0
  repository: http://logicLAB.jira.com/svn/BDKPO
version: 0.06
