---
name: Business-DK-PO
version: 0.03
author:
  - 'Jonas B. Nielsen, (jonasbn) <jonasbn@cpan.org>'
abstract: a danish postal order code generator/validator
license: artistic
resources:
  license: http://opensource.org/licenses/artistic-license.php
requires:
  Carp: 0
  Exporter: 0
  Test::Exception: 0
provides:
  Business::DK::PO:
    file: lib/Business/DK/PO.pm
    version: 0.03
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
